### PR TITLE
support for M.[ foo ], M.{ foo }, etc.

### PR DESCRIPTION
**Pull request by gasche**
This is a proposal implementation of the approach suggested by Jérémie
in github issue #10. I had to protect the expr production

```
| m = a_UIDENT; "."; l = SELF -> <:ident< $uid:m$.$l$ >>
```

with a TRY around [ "."; SELF ], because otherwise it would fire
in the M.<delim> case, eat the last dot, and then fail with a parse
error on the delimiter.

PS: take this code with a grain of salt. I compiled and (lightly) tested it in the ocaml 4.00 branch (I haven't done the not-totally-obvious work of getting separate-camlp4 to compile on my machine yet). And camlp4 parsing is always very tricky. It's more meant for review and inspiration than for actual inclusion.

### CODE REVIEW

**Comment by gasche** [comment]
@diml , do you have any feedback on the proposed patch?

(Do you know if there is a specific plan regarding the timeline for integrating trunk syntactic changes in camlp4? Do you or does someone else plan to make all changes, in one batch, around the time of the next OCaml release?)

**Comment by ghost** [comment]
IIRC, I did try it but there were some problems. I'll give it another try.

For the other syntactic changes, I integrated part of them (module aliases and generative functors). I still have to do the functor sig types simplification. Feel free to open tickets if you can think of other changes. The plan is basically to have the syntactic changes in camlp4 between the time they are added to trunk and the next release (but not too soon in case they change in trunk, to avoid unnecessary work).

**Comment by damiendoligez** [comment]
I think the syntax is relatively stable now, but anyway I can guarantee that there will be no significant change between the upcoming beta release (beginning of May) until the final release (end of June), so you should probably plan to complete the work within that window.

**Comment by ghost** [comment]
I fixed and applied the patch.

**Pull request closed without merging**
