### PR TITLE
Add support for OCaml 4.13

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Review by gasche — APPROVED** [review]
The changes look nice. I don't know what's the branch strategy on this repository; the current PR is against trunk, should it also go somewhere else? 

cc @ygrek

**Comment by ygrek** [comment]
iirc trunk follows ocaml trunk and older versions are tagged/branched in case additional release needed (so far didn't happen)

**Comment by kit-ty-kate** [comment]
OCaml 4.13 si due to be released in the next couple of week(s). I've been testing this PR even since and I haven't detected any issues with it. Is there any chance a release could be done?

**Comment by ygrek** [comment]
thanks, sorry for delaying (added you to the camlp4 org)

**Pull request merged**
