### PR TITLE
Add DESTDIR support

### PR DESCRIPTION
**Pull request by olafhering**
When building rpm packages it is required to install the resulting
binaries below an "offset" directory. Such directory is specified with
make DESTDIR=$RPM_BUILD_ROOT in almost all packages.

Without this change make install will fail. Using make
SOME_DIRECTORY_VARIABLE=$RPM_BUILD_ROOT/$WHATEVER_WAS_IN_SOME_DIRECTORY_VARIABLE
will fail when SOME_DIRECTORY_VARIABLE is compiled into the binaries.
The offset will become part of the desired directories. This leads to
runtime errors. And it leads to package build failures because the
post-build checks scan for RPM_BUILD_ROOT usage in binaries.

Signed-off-by: Olaf Hering olaf@aepfle.de

### CODE REVIEW

**Comment by ghost** [comment]
fine by me

**Comment by avsm** [comment]
for reference, the spec file I've been using for camlp4 is here:
https://build.opensuse.org/package/view_file/home:ocaml/camlp4/ocaml-camlp4.spec?expand=1

(only the make install target includes the destdir)

**Comment by olafhering** [comment]
Yes, and exactly this usage of internal variables is not supposed to happen.
Just make DESTDIR=x has to be enough.

**Comment by avsm** [comment]
Yes, DESTDIR is preferable.

**Pull request merged**
