### PR TITLE
Update META.in

### PR DESCRIPTION
**Pull request by whitequark**
Use ^ocaml/camlp4 to achieve the same result as +camlp4 for system opam switch.

Refs #30

### CODE REVIEW

**Comment by avsm** [comment]
Something is definitely needed here, as the `system` compiler when used with `camlp4` breaks on type_conv at the moment (a major blocker):

In my `system` setup of 4.02, camlp4 gets installed into:

```
/home/avsm/.opam/system/lib/ocaml/camlp4/Camlp4Parsers/Camlp4OCamlOriginalQuotationExpander.cmi
...etc
```

so we want `ocamlfind` to return `/home/avsm/.opam/system/lib/ocaml/camlp4/`.  This is slightly unusual -- why not just install camlp4 into `.opam/system/lib/camlp4` just like any other ocamlfind package?

I couldn't get the `^ocaml/camlp4` suggestion here to work unfortunately.  That returns:

```
$ ocamlfind query -format %d camlp4 
/home/avsm/ocaml402/lib/ocaml/ocaml/camlp4
# my system compiler is in /home/avsm/ocaml402, so this is wrong
```

A purely relative path via `ocaml/camlp4` doesn't work either, since `camlp4/` is prefixed.

```
$ ocamlfind query -format %d camlp4 
/home/avsm/.opam/system/lib/camlp4/ocaml/camlp4
```

So, one fix would be to install camlp4 without the `ocaml/` prefix -- any reason not to do this @diml?  It would be good to get this sorted and tagged so we can do bulk builds in OPAM ahead of the 4.02.0 release.

**Comment by avsm** [comment]
Both `type_conv` and `ulex` fail due to this; see https://travis-ci.org/mirage/ocaml-cow/jobs/33594662

**Comment by ghost** [comment]
Well `ulex` is a typical example of why installing camlp4 without the `ocaml/` prefix as before is a breaking change. For instance if you try the following it will fail:

```
opam init
opam install camlp4
mv `opam config var root`/system/lib/{ocaml/camlp4,camlp4}
opam install ulex
```

The reason is that ulex doesn't use `ocamlfind` to build. If you look at the instruction that fail:

```
/usr/bin/ocamlc.opt -c -I +camlp4 -pp camlp4orf -o pa_ulex.cmo pa_ulex.ml
```

Here the `+camlp4` will always resolve to the `$(ocamlc -where)/camlp4` which contains the `ocaml/` prefix. Actually in the travis example build it would be `/usr/lib/ocaml/camlp4` which is even worse.

The solution is to fix the build systems of all packages that don't use ocamlfind to build.

**Comment by avsm** [comment]
This is superseded by #43

**Pull request closed without merging**
