### PR TITLE
Upgrade to OCaml 4.14

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Comment by ygrek** [comment]
ftr you can push to master if you feel like it

**Comment by ygrek** [comment]
checked builds, merged, thanks!

**Comment by kit-ty-kate** [comment]
> ftr you can push to master if you feel like it

I don’t seem to have the rights on this repository, only on the `camlp4` github organisation (i.e. I can create new repositories in `camlp4` but not merge, push or close any issues in this repository)

**Comment by gasche** [comment]
I took the initiative to give repository access to @kit-ty-kate. Thanks for your work!

**Pull request merged**
