### PR TITLE
Make camlp4 insensitive to CDPATH.

### PR DESCRIPTION
**Pull request by whitequark**
Ref: https://github.com/ocaml/opam-repository/issues/2561.

This is the second time I encounter this bug, and I've seen people on IRC occasionally come in with the same report. I believe there are no downside to these changes, and while the problem is fairly obscure, I think this is worth merging.

It's interesting that practically nothing except camlp4 uses cd in build scripts.

### CODE REVIEW

**Comment by ghost** [comment]
Yeah I just copy & pasted the script from ocaml. I didn't changed them too much assuming they used to work, to avoid breaking someone else setup... But this part could certainly be improved.

I'm just a bit dubious about this:

```
cd ./`dirname $0`/..
```

Is it safe to assume `$0` will always be relative?

**Comment by whitequark** [comment]
Fixed.

**Comment by ghost** [comment]
I'm not sure `realpath` is portable, it doesn't even work with dash. I think we should just replace all the `cd $(dirname $0)/..` by something like:

``` sh
if [ ! -e camlp4/META.in ] ; then
  echo "script $0 invoked from the wrong location"
  exit 1
fi
```

**Comment by avsm** [comment]
thats right -- realpath doesnt work on macos x either, and various shell gymnastics are required.  the below looks good.

**Comment by whitequark** [comment]
Fixed

**Comment by ghost** [comment]
Thanks! I'll do a release soon with the fix.

**Pull request merged**
