### PR TITLE
Add support for OCaml 5.0

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Review by gasche — APPROVED** [review]
This looks good to me. The ocamlbuild switch from "not using ocamlfind" to "using ocamlfind" is a relatively big build-system change (as far as those go), and it's good news that it didn't break anything because it might have. I guess that `-no-ocamlfind` was used before just to be conservative about previous behavior, and not for some unknown/unclear Very Important Reason. Nice work!

Note: due to the switch from Pervasives to Result, the codebase will not support older OCaml releases, but I believe there is no need with camlp4's one-branch-per-ocaml-version conventions.

**Comment by kit-ty-kate** [comment]
I was gonna do a release but then `git push` broke and i realized @ygrek made a different set of change in the `5.0` branch already.. I'm not sure what to do now.

**Comment by ygrek** [comment]
afaics the changes are essentially the same so can just merge 5.0 with trunk and tag that for release

**Comment by vsiles** [comment]
Hi folks ! Do you have an ETA of when the 5.0 support will be available via opam ? Thanks !

**Pull request merged**
