### PR TITLE
fix build and improve the Travis script to install ocamlfind

### PR DESCRIPTION
**Pull request by avsm**
Necessary from the shift to findlib installation in ade6468a2e6c202

### CODE REVIEW

**Comment by avsm** [comment]
@diml, I slipped the 4.02.0+rc1 tag to the head of this pull request (c84c713d8ce48349fae7ffd00a20688aa46dcf22)

**Comment by avsm** [comment]
I stuck a release note about camlp4 to https://github.com/ocaml/camlp4/releases/tag/4.02.0%2Brc1 -- anything else to edit in there @diml or @whitequark? (about ppx?)

**Comment by ghost** [comment]
@avsm, I see that you put the tag on trunk. trunk is supposed to follow the trunk branch of ocaml, the tag should have gone on the 4.02 branch.

**Comment by avsm** [comment]
Woops, my apologies...I'll slip the tag properly and update the pull request to OPAM.

**Comment by avsm** [comment]
Actually @diml -- 4.02 needs the findlib changes merged as well.  Can you merge those and add the tag to stop us from overlapping? I'm about to go offline for a couple of hours.

**Comment by avsm** [comment]
(I sent my pull request to trunk, not 4.02)

**Comment by ghost** [comment]
Done.

**Comment by whitequark** [comment]
@avsm Something like:

```
Note that camlp4 is considered deprecated since OCaml 4.02. New syntax extensions are encouraged to use the extension points (ppx) mechanism.
```

**Comment by avsm** [comment]
I don't think camlp4 has been officially deprecated -- it's just been moved outside the official release for this time.  I think the killing stroke comes much later once extension points have been adopted and code has migrated (but I might be wrong).

**Comment by whitequark** [comment]
@avsm I have heard the statements from various core developers towards the point that camlp4 is in maintenance-only mode now and is not recommended when you can avoid it. That sounds like deprecation to me.

**Comment by avsm** [comment]
It's a two-phase commit: the attempt to deprecate camlp4 has started, but it will only happen in practise when the bulk of code using it has migrated elsewhere.  A _lot_ of OPAM packages depend on camlp4.

**Comment by dsheets** [comment]
Does ppx offer something like quotations/antiquotations? I agree camlp4 seems heavyweight for a lot of uses but what would something like mirage/ocaml-cow migrate to?

**Comment by whitequark** [comment]
@dsheets Yes, using the `{foo| ... |foo}` strings. (You will have to parse whatever is inside the string yourself).

**Pull request merged**
